[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
staking_program = "aF5FEXUVz3fFyycXFZ3TaxcAqbHdejbVBk5xneDHcqA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
