[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
nft_staking_program = "GxEQegvykBHF8c2kFqsaNQr2UzDYybnndp8DtCmbNbeW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hot-pepper/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
