[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
counter_program = "HvdLQzQTmZsmpcjZpbRM87RNYcf24YxfGrv8mj2hDkzH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
